# coding: utf-8

"""
    🐕 Kelpie API

    API for running long jobs on Salad  # noqa: E501

    OpenAPI spec version: 0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response202 import InlineResponse202  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse202(unittest.TestCase):
    """InlineResponse202 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse202(self):
        """Test InlineResponse202"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response202.InlineResponse202()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
