# coding: utf-8

"""
    🐕 Kelpie API

    API for running long jobs on Salad  # noqa: E501

    OpenAPI spec version: 0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.id_heartbeat_body import IdHeartbeatBody  # noqa: E501
from swagger_client.rest import ApiException


class TestIdHeartbeatBody(unittest.TestCase):
    """IdHeartbeatBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdHeartbeatBody(self):
        """Test IdHeartbeatBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.id_heartbeat_body.IdHeartbeatBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
