# coding: utf-8

"""
    🐕 Kelpie API

    API for running long jobs on Salad  # noqa: E501

    OpenAPI spec version: 0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_cancel_job(self):
        """Test case for delete_cancel_job

        Cancel job  # noqa: E501
        """
        pass

    def test_delete_clear_jobs(self):
        """Test case for delete_clear_jobs

        (ADMIN) Clear all jobs  # noqa: E501
        """
        pass

    def test_delete_clear_scaling_rules(self):
        """Test case for delete_clear_scaling_rules

        (ADMIN) Clear all scaling rules  # noqa: E501
        """
        pass

    def test_delete_clear_users(self):
        """Test case for delete_clear_users

        (ADMIN) Clear all users  # noqa: E501
        """
        pass

    def test_delete_delete_scaling_rule(self):
        """Test case for delete_delete_scaling_rule

        Delete a scaling rule  # noqa: E501
        """
        pass

    def test_get_get_job(self):
        """Test case for get_get_job

        Get a job  # noqa: E501
        """
        pass

    def test_get_get_scaling_rule(self):
        """Test case for get_get_scaling_rule

        Get a scaling rule  # noqa: E501
        """
        pass

    def test_get_get_work(self):
        """Test case for get_get_work

        Get work  # noqa: E501
        """
        pass

    def test_get_list_jobs(self):
        """Test case for get_list_jobs

        List jobs  # noqa: E501
        """
        pass

    def test_get_list_scaling_rules(self):
        """Test case for get_list_scaling_rules

        List all scaling rules  # noqa: E501
        """
        pass

    def test_patch_update_scaling_rule(self):
        """Test case for patch_update_scaling_rule

        Update an existing scaling rule  # noqa: E501
        """
        pass

    def test_post_batch_create_jobs(self):
        """Test case for post_batch_create_jobs

        Queue multiple jobs  # noqa: E501
        """
        pass

    def test_post_create_job(self):
        """Test case for post_create_job

        Queue a new job  # noqa: E501
        """
        pass

    def test_post_create_scaling_rule(self):
        """Test case for post_create_scaling_rule

        Create a new scaling rule  # noqa: E501
        """
        pass

    def test_post_create_token(self):
        """Test case for post_create_token

        (ADMIN) Create a new token  # noqa: E501
        """
        pass

    def test_post_create_user(self):
        """Test case for post_create_user

        (ADMIN) Create a new user  # noqa: E501
        """
        pass

    def test_post_job_heartbeat(self):
        """Test case for post_job_heartbeat

        Job heartbeat  # noqa: E501
        """
        pass

    def test_post_report_job_completed(self):
        """Test case for post_report_job_completed

        Report job completed  # noqa: E501
        """
        pass

    def test_post_report_job_failure(self):
        """Test case for post_report_job_failure

        Report job failure  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
