# coding: utf-8

"""
    🐕 Kelpie API

    API for running long jobs on Salad  # noqa: E501

    OpenAPI spec version: 0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.id_failed_body import IdFailedBody  # noqa: E501
from swagger_client.rest import ApiException


class TestIdFailedBody(unittest.TestCase):
    """IdFailedBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdFailedBody(self):
        """Test IdFailedBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.id_failed_body.IdFailedBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
