# coding: utf-8

# flake8: noqa
"""
    🐕 Kelpie API

    API for running long jobs on Salad  # noqa: E501

    OpenAPI spec version: 0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.id_completed_body import IdCompletedBody
from swagger_client.models.id_failed_body import IdFailedBody
from swagger_client.models.id_heartbeat_body import IdHeartbeatBody
from swagger_client.models.id_token_body import IdTokenBody
from swagger_client.models.inline_response200 import InlineResponse200
from swagger_client.models.inline_response2001 import InlineResponse2001
from swagger_client.models.inline_response2002 import InlineResponse2002
from swagger_client.models.inline_response201 import InlineResponse201
from swagger_client.models.inline_response2011 import InlineResponse2011
from swagger_client.models.inline_response2012 import InlineResponse2012
from swagger_client.models.inline_response202 import InlineResponse202
from swagger_client.models.inline_response204 import InlineResponse204
from swagger_client.models.inline_response400 import InlineResponse400
from swagger_client.models.jobs_body import JobsBody
from swagger_client.models.jobs_sync import JobsSync
from swagger_client.models.scalingrules_body import ScalingrulesBody
from swagger_client.models.scalingrules_id_body import ScalingrulesIdBody
from swagger_client.models.users_body import UsersBody
