# coding: utf-8

"""
    🐕 Kelpie API

    API for running long jobs on Salad  # noqa: E501

    OpenAPI spec version: 0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IdFailedBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'machine_id': 'object',
        'container_group_id': 'object'
    }

    attribute_map = {
        'machine_id': 'machine_id',
        'container_group_id': 'container_group_id'
    }

    def __init__(self, machine_id=None, container_group_id=None):  # noqa: E501
        """IdFailedBody - a model defined in Swagger"""  # noqa: E501
        self._machine_id = None
        self._container_group_id = None
        self.discriminator = None
        self.machine_id = machine_id
        self.container_group_id = container_group_id

    @property
    def machine_id(self):
        """Gets the machine_id of this IdFailedBody.  # noqa: E501


        :return: The machine_id of this IdFailedBody.  # noqa: E501
        :rtype: object
        """
        return self._machine_id

    @machine_id.setter
    def machine_id(self, machine_id):
        """Sets the machine_id of this IdFailedBody.


        :param machine_id: The machine_id of this IdFailedBody.  # noqa: E501
        :type: object
        """
        if machine_id is None:
            raise ValueError("Invalid value for `machine_id`, must not be `None`")  # noqa: E501

        self._machine_id = machine_id

    @property
    def container_group_id(self):
        """Gets the container_group_id of this IdFailedBody.  # noqa: E501


        :return: The container_group_id of this IdFailedBody.  # noqa: E501
        :rtype: object
        """
        return self._container_group_id

    @container_group_id.setter
    def container_group_id(self, container_group_id):
        """Sets the container_group_id of this IdFailedBody.


        :param container_group_id: The container_group_id of this IdFailedBody.  # noqa: E501
        :type: object
        """
        if container_group_id is None:
            raise ValueError("Invalid value for `container_group_id`, must not be `None`")  # noqa: E501

        self._container_group_id = container_group_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IdFailedBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IdFailedBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
