# coding: utf-8

"""
    🐕 Kelpie API

    API for running long jobs on Salad  # noqa: E501

    OpenAPI spec version: 0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse201(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'container_group_id': 'object',
        'min_replicas': 'object',
        'max_replicas': 'object',
        'idle_threshold_seconds': 'object',
        'org_name': 'object',
        'project_name': 'object',
        'container_group_name': 'object',
        'user_id': 'object',
        'created': 'object',
        'updated': 'object'
    }

    attribute_map = {
        'container_group_id': 'container_group_id',
        'min_replicas': 'min_replicas',
        'max_replicas': 'max_replicas',
        'idle_threshold_seconds': 'idle_threshold_seconds',
        'org_name': 'org_name',
        'project_name': 'project_name',
        'container_group_name': 'container_group_name',
        'user_id': 'user_id',
        'created': 'created',
        'updated': 'updated'
    }

    def __init__(self, container_group_id=None, min_replicas=None, max_replicas=None, idle_threshold_seconds=None, org_name=None, project_name=None, container_group_name=None, user_id=None, created=None, updated=None):  # noqa: E501
        """InlineResponse201 - a model defined in Swagger"""  # noqa: E501
        self._container_group_id = None
        self._min_replicas = None
        self._max_replicas = None
        self._idle_threshold_seconds = None
        self._org_name = None
        self._project_name = None
        self._container_group_name = None
        self._user_id = None
        self._created = None
        self._updated = None
        self.discriminator = None
        self.container_group_id = container_group_id
        self.min_replicas = min_replicas
        self.max_replicas = max_replicas
        self.idle_threshold_seconds = idle_threshold_seconds
        self.org_name = org_name
        self.project_name = project_name
        self.container_group_name = container_group_name
        self.user_id = user_id
        self.created = created
        if updated is not None:
            self.updated = updated

    @property
    def container_group_id(self):
        """Gets the container_group_id of this InlineResponse201.  # noqa: E501


        :return: The container_group_id of this InlineResponse201.  # noqa: E501
        :rtype: object
        """
        return self._container_group_id

    @container_group_id.setter
    def container_group_id(self, container_group_id):
        """Sets the container_group_id of this InlineResponse201.


        :param container_group_id: The container_group_id of this InlineResponse201.  # noqa: E501
        :type: object
        """
        if container_group_id is None:
            raise ValueError("Invalid value for `container_group_id`, must not be `None`")  # noqa: E501

        self._container_group_id = container_group_id

    @property
    def min_replicas(self):
        """Gets the min_replicas of this InlineResponse201.  # noqa: E501


        :return: The min_replicas of this InlineResponse201.  # noqa: E501
        :rtype: object
        """
        return self._min_replicas

    @min_replicas.setter
    def min_replicas(self, min_replicas):
        """Sets the min_replicas of this InlineResponse201.


        :param min_replicas: The min_replicas of this InlineResponse201.  # noqa: E501
        :type: object
        """
        if min_replicas is None:
            raise ValueError("Invalid value for `min_replicas`, must not be `None`")  # noqa: E501

        self._min_replicas = min_replicas

    @property
    def max_replicas(self):
        """Gets the max_replicas of this InlineResponse201.  # noqa: E501


        :return: The max_replicas of this InlineResponse201.  # noqa: E501
        :rtype: object
        """
        return self._max_replicas

    @max_replicas.setter
    def max_replicas(self, max_replicas):
        """Sets the max_replicas of this InlineResponse201.


        :param max_replicas: The max_replicas of this InlineResponse201.  # noqa: E501
        :type: object
        """
        if max_replicas is None:
            raise ValueError("Invalid value for `max_replicas`, must not be `None`")  # noqa: E501

        self._max_replicas = max_replicas

    @property
    def idle_threshold_seconds(self):
        """Gets the idle_threshold_seconds of this InlineResponse201.  # noqa: E501


        :return: The idle_threshold_seconds of this InlineResponse201.  # noqa: E501
        :rtype: object
        """
        return self._idle_threshold_seconds

    @idle_threshold_seconds.setter
    def idle_threshold_seconds(self, idle_threshold_seconds):
        """Sets the idle_threshold_seconds of this InlineResponse201.


        :param idle_threshold_seconds: The idle_threshold_seconds of this InlineResponse201.  # noqa: E501
        :type: object
        """
        if idle_threshold_seconds is None:
            raise ValueError("Invalid value for `idle_threshold_seconds`, must not be `None`")  # noqa: E501

        self._idle_threshold_seconds = idle_threshold_seconds

    @property
    def org_name(self):
        """Gets the org_name of this InlineResponse201.  # noqa: E501


        :return: The org_name of this InlineResponse201.  # noqa: E501
        :rtype: object
        """
        return self._org_name

    @org_name.setter
    def org_name(self, org_name):
        """Sets the org_name of this InlineResponse201.


        :param org_name: The org_name of this InlineResponse201.  # noqa: E501
        :type: object
        """
        if org_name is None:
            raise ValueError("Invalid value for `org_name`, must not be `None`")  # noqa: E501

        self._org_name = org_name

    @property
    def project_name(self):
        """Gets the project_name of this InlineResponse201.  # noqa: E501


        :return: The project_name of this InlineResponse201.  # noqa: E501
        :rtype: object
        """
        return self._project_name

    @project_name.setter
    def project_name(self, project_name):
        """Sets the project_name of this InlineResponse201.


        :param project_name: The project_name of this InlineResponse201.  # noqa: E501
        :type: object
        """
        if project_name is None:
            raise ValueError("Invalid value for `project_name`, must not be `None`")  # noqa: E501

        self._project_name = project_name

    @property
    def container_group_name(self):
        """Gets the container_group_name of this InlineResponse201.  # noqa: E501


        :return: The container_group_name of this InlineResponse201.  # noqa: E501
        :rtype: object
        """
        return self._container_group_name

    @container_group_name.setter
    def container_group_name(self, container_group_name):
        """Sets the container_group_name of this InlineResponse201.


        :param container_group_name: The container_group_name of this InlineResponse201.  # noqa: E501
        :type: object
        """
        if container_group_name is None:
            raise ValueError("Invalid value for `container_group_name`, must not be `None`")  # noqa: E501

        self._container_group_name = container_group_name

    @property
    def user_id(self):
        """Gets the user_id of this InlineResponse201.  # noqa: E501


        :return: The user_id of this InlineResponse201.  # noqa: E501
        :rtype: object
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this InlineResponse201.


        :param user_id: The user_id of this InlineResponse201.  # noqa: E501
        :type: object
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def created(self):
        """Gets the created of this InlineResponse201.  # noqa: E501


        :return: The created of this InlineResponse201.  # noqa: E501
        :rtype: object
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this InlineResponse201.


        :param created: The created of this InlineResponse201.  # noqa: E501
        :type: object
        """
        if created is None:
            raise ValueError("Invalid value for `created`, must not be `None`")  # noqa: E501

        self._created = created

    @property
    def updated(self):
        """Gets the updated of this InlineResponse201.  # noqa: E501


        :return: The updated of this InlineResponse201.  # noqa: E501
        :rtype: object
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this InlineResponse201.


        :param updated: The updated of this InlineResponse201.  # noqa: E501
        :type: object
        """

        self._updated = updated

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse201, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse201):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
