# coding: utf-8

"""
    🐕 Kelpie API

    API for running long jobs on Salad  # noqa: E501

    OpenAPI spec version: 0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse202(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'user_id': 'object',
        'status': 'object',
        'created': 'object',
        'started': 'object',
        'completed': 'object',
        'canceled': 'object',
        'failed': 'object',
        'heartbeat': 'object',
        'num_failures': 'object',
        'machine_id': 'object',
        'num_heartbeats': 'object',
        'command': 'object',
        'arguments': 'object',
        'environment': 'object',
        'input_bucket': 'object',
        'input_prefix': 'object',
        'checkpoint_bucket': 'object',
        'checkpoint_prefix': 'object',
        'output_bucket': 'object',
        'output_prefix': 'object',
        'max_failures': 'object',
        'heartbeat_interval': 'object',
        'webhook': 'object',
        'container_group_id': 'object',
        'compression': 'object',
        'sync': 'JobsSync'
    }

    attribute_map = {
        'id': 'id',
        'user_id': 'user_id',
        'status': 'status',
        'created': 'created',
        'started': 'started',
        'completed': 'completed',
        'canceled': 'canceled',
        'failed': 'failed',
        'heartbeat': 'heartbeat',
        'num_failures': 'num_failures',
        'machine_id': 'machine_id',
        'num_heartbeats': 'num_heartbeats',
        'command': 'command',
        'arguments': 'arguments',
        'environment': 'environment',
        'input_bucket': 'input_bucket',
        'input_prefix': 'input_prefix',
        'checkpoint_bucket': 'checkpoint_bucket',
        'checkpoint_prefix': 'checkpoint_prefix',
        'output_bucket': 'output_bucket',
        'output_prefix': 'output_prefix',
        'max_failures': 'max_failures',
        'heartbeat_interval': 'heartbeat_interval',
        'webhook': 'webhook',
        'container_group_id': 'container_group_id',
        'compression': 'compression',
        'sync': 'sync'
    }

    def __init__(self, id=None, user_id=None, status=None, created=None, started=None, completed=None, canceled=None, failed=None, heartbeat=None, num_failures=None, machine_id=None, num_heartbeats=None, command=None, arguments=None, environment=None, input_bucket=None, input_prefix=None, checkpoint_bucket=None, checkpoint_prefix=None, output_bucket=None, output_prefix=None, max_failures=None, heartbeat_interval=None, webhook=None, container_group_id=None, compression=None, sync=None):  # noqa: E501
        """InlineResponse202 - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._user_id = None
        self._status = None
        self._created = None
        self._started = None
        self._completed = None
        self._canceled = None
        self._failed = None
        self._heartbeat = None
        self._num_failures = None
        self._machine_id = None
        self._num_heartbeats = None
        self._command = None
        self._arguments = None
        self._environment = None
        self._input_bucket = None
        self._input_prefix = None
        self._checkpoint_bucket = None
        self._checkpoint_prefix = None
        self._output_bucket = None
        self._output_prefix = None
        self._max_failures = None
        self._heartbeat_interval = None
        self._webhook = None
        self._container_group_id = None
        self._compression = None
        self._sync = None
        self.discriminator = None
        self.id = id
        self.user_id = user_id
        self.status = status
        self.created = created
        if started is not None:
            self.started = started
        if completed is not None:
            self.completed = completed
        if canceled is not None:
            self.canceled = canceled
        if failed is not None:
            self.failed = failed
        if heartbeat is not None:
            self.heartbeat = heartbeat
        if num_failures is not None:
            self.num_failures = num_failures
        if machine_id is not None:
            self.machine_id = machine_id
        if num_heartbeats is not None:
            self.num_heartbeats = num_heartbeats
        self.command = command
        if arguments is not None:
            self.arguments = arguments
        if environment is not None:
            self.environment = environment
        if input_bucket is not None:
            self.input_bucket = input_bucket
        if input_prefix is not None:
            self.input_prefix = input_prefix
        if checkpoint_bucket is not None:
            self.checkpoint_bucket = checkpoint_bucket
        if checkpoint_prefix is not None:
            self.checkpoint_prefix = checkpoint_prefix
        if output_bucket is not None:
            self.output_bucket = output_bucket
        if output_prefix is not None:
            self.output_prefix = output_prefix
        if max_failures is not None:
            self.max_failures = max_failures
        if heartbeat_interval is not None:
            self.heartbeat_interval = heartbeat_interval
        if webhook is not None:
            self.webhook = webhook
        self.container_group_id = container_group_id
        if compression is not None:
            self.compression = compression
        if sync is not None:
            self.sync = sync

    @property
    def id(self):
        """Gets the id of this InlineResponse202.  # noqa: E501


        :return: The id of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse202.


        :param id: The id of this InlineResponse202.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def user_id(self):
        """Gets the user_id of this InlineResponse202.  # noqa: E501


        :return: The user_id of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this InlineResponse202.


        :param user_id: The user_id of this InlineResponse202.  # noqa: E501
        :type: object
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def status(self):
        """Gets the status of this InlineResponse202.  # noqa: E501


        :return: The status of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse202.


        :param status: The status of this InlineResponse202.  # noqa: E501
        :type: object
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def created(self):
        """Gets the created of this InlineResponse202.  # noqa: E501


        :return: The created of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this InlineResponse202.


        :param created: The created of this InlineResponse202.  # noqa: E501
        :type: object
        """
        if created is None:
            raise ValueError("Invalid value for `created`, must not be `None`")  # noqa: E501

        self._created = created

    @property
    def started(self):
        """Gets the started of this InlineResponse202.  # noqa: E501


        :return: The started of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._started

    @started.setter
    def started(self, started):
        """Sets the started of this InlineResponse202.


        :param started: The started of this InlineResponse202.  # noqa: E501
        :type: object
        """

        self._started = started

    @property
    def completed(self):
        """Gets the completed of this InlineResponse202.  # noqa: E501


        :return: The completed of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._completed

    @completed.setter
    def completed(self, completed):
        """Sets the completed of this InlineResponse202.


        :param completed: The completed of this InlineResponse202.  # noqa: E501
        :type: object
        """

        self._completed = completed

    @property
    def canceled(self):
        """Gets the canceled of this InlineResponse202.  # noqa: E501


        :return: The canceled of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._canceled

    @canceled.setter
    def canceled(self, canceled):
        """Sets the canceled of this InlineResponse202.


        :param canceled: The canceled of this InlineResponse202.  # noqa: E501
        :type: object
        """

        self._canceled = canceled

    @property
    def failed(self):
        """Gets the failed of this InlineResponse202.  # noqa: E501


        :return: The failed of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._failed

    @failed.setter
    def failed(self, failed):
        """Sets the failed of this InlineResponse202.


        :param failed: The failed of this InlineResponse202.  # noqa: E501
        :type: object
        """

        self._failed = failed

    @property
    def heartbeat(self):
        """Gets the heartbeat of this InlineResponse202.  # noqa: E501


        :return: The heartbeat of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._heartbeat

    @heartbeat.setter
    def heartbeat(self, heartbeat):
        """Sets the heartbeat of this InlineResponse202.


        :param heartbeat: The heartbeat of this InlineResponse202.  # noqa: E501
        :type: object
        """

        self._heartbeat = heartbeat

    @property
    def num_failures(self):
        """Gets the num_failures of this InlineResponse202.  # noqa: E501


        :return: The num_failures of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._num_failures

    @num_failures.setter
    def num_failures(self, num_failures):
        """Sets the num_failures of this InlineResponse202.


        :param num_failures: The num_failures of this InlineResponse202.  # noqa: E501
        :type: object
        """

        self._num_failures = num_failures

    @property
    def machine_id(self):
        """Gets the machine_id of this InlineResponse202.  # noqa: E501


        :return: The machine_id of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._machine_id

    @machine_id.setter
    def machine_id(self, machine_id):
        """Sets the machine_id of this InlineResponse202.


        :param machine_id: The machine_id of this InlineResponse202.  # noqa: E501
        :type: object
        """

        self._machine_id = machine_id

    @property
    def num_heartbeats(self):
        """Gets the num_heartbeats of this InlineResponse202.  # noqa: E501


        :return: The num_heartbeats of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._num_heartbeats

    @num_heartbeats.setter
    def num_heartbeats(self, num_heartbeats):
        """Sets the num_heartbeats of this InlineResponse202.


        :param num_heartbeats: The num_heartbeats of this InlineResponse202.  # noqa: E501
        :type: object
        """

        self._num_heartbeats = num_heartbeats

    @property
    def command(self):
        """Gets the command of this InlineResponse202.  # noqa: E501


        :return: The command of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._command

    @command.setter
    def command(self, command):
        """Sets the command of this InlineResponse202.


        :param command: The command of this InlineResponse202.  # noqa: E501
        :type: object
        """
        if command is None:
            raise ValueError("Invalid value for `command`, must not be `None`")  # noqa: E501

        self._command = command

    @property
    def arguments(self):
        """Gets the arguments of this InlineResponse202.  # noqa: E501


        :return: The arguments of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._arguments

    @arguments.setter
    def arguments(self, arguments):
        """Sets the arguments of this InlineResponse202.


        :param arguments: The arguments of this InlineResponse202.  # noqa: E501
        :type: object
        """

        self._arguments = arguments

    @property
    def environment(self):
        """Gets the environment of this InlineResponse202.  # noqa: E501


        :return: The environment of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._environment

    @environment.setter
    def environment(self, environment):
        """Sets the environment of this InlineResponse202.


        :param environment: The environment of this InlineResponse202.  # noqa: E501
        :type: object
        """

        self._environment = environment

    @property
    def input_bucket(self):
        """Gets the input_bucket of this InlineResponse202.  # noqa: E501


        :return: The input_bucket of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._input_bucket

    @input_bucket.setter
    def input_bucket(self, input_bucket):
        """Sets the input_bucket of this InlineResponse202.


        :param input_bucket: The input_bucket of this InlineResponse202.  # noqa: E501
        :type: object
        """

        self._input_bucket = input_bucket

    @property
    def input_prefix(self):
        """Gets the input_prefix of this InlineResponse202.  # noqa: E501


        :return: The input_prefix of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._input_prefix

    @input_prefix.setter
    def input_prefix(self, input_prefix):
        """Sets the input_prefix of this InlineResponse202.


        :param input_prefix: The input_prefix of this InlineResponse202.  # noqa: E501
        :type: object
        """

        self._input_prefix = input_prefix

    @property
    def checkpoint_bucket(self):
        """Gets the checkpoint_bucket of this InlineResponse202.  # noqa: E501


        :return: The checkpoint_bucket of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._checkpoint_bucket

    @checkpoint_bucket.setter
    def checkpoint_bucket(self, checkpoint_bucket):
        """Sets the checkpoint_bucket of this InlineResponse202.


        :param checkpoint_bucket: The checkpoint_bucket of this InlineResponse202.  # noqa: E501
        :type: object
        """

        self._checkpoint_bucket = checkpoint_bucket

    @property
    def checkpoint_prefix(self):
        """Gets the checkpoint_prefix of this InlineResponse202.  # noqa: E501


        :return: The checkpoint_prefix of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._checkpoint_prefix

    @checkpoint_prefix.setter
    def checkpoint_prefix(self, checkpoint_prefix):
        """Sets the checkpoint_prefix of this InlineResponse202.


        :param checkpoint_prefix: The checkpoint_prefix of this InlineResponse202.  # noqa: E501
        :type: object
        """

        self._checkpoint_prefix = checkpoint_prefix

    @property
    def output_bucket(self):
        """Gets the output_bucket of this InlineResponse202.  # noqa: E501


        :return: The output_bucket of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._output_bucket

    @output_bucket.setter
    def output_bucket(self, output_bucket):
        """Sets the output_bucket of this InlineResponse202.


        :param output_bucket: The output_bucket of this InlineResponse202.  # noqa: E501
        :type: object
        """

        self._output_bucket = output_bucket

    @property
    def output_prefix(self):
        """Gets the output_prefix of this InlineResponse202.  # noqa: E501


        :return: The output_prefix of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._output_prefix

    @output_prefix.setter
    def output_prefix(self, output_prefix):
        """Sets the output_prefix of this InlineResponse202.


        :param output_prefix: The output_prefix of this InlineResponse202.  # noqa: E501
        :type: object
        """

        self._output_prefix = output_prefix

    @property
    def max_failures(self):
        """Gets the max_failures of this InlineResponse202.  # noqa: E501


        :return: The max_failures of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._max_failures

    @max_failures.setter
    def max_failures(self, max_failures):
        """Sets the max_failures of this InlineResponse202.


        :param max_failures: The max_failures of this InlineResponse202.  # noqa: E501
        :type: object
        """

        self._max_failures = max_failures

    @property
    def heartbeat_interval(self):
        """Gets the heartbeat_interval of this InlineResponse202.  # noqa: E501


        :return: The heartbeat_interval of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._heartbeat_interval

    @heartbeat_interval.setter
    def heartbeat_interval(self, heartbeat_interval):
        """Sets the heartbeat_interval of this InlineResponse202.


        :param heartbeat_interval: The heartbeat_interval of this InlineResponse202.  # noqa: E501
        :type: object
        """

        self._heartbeat_interval = heartbeat_interval

    @property
    def webhook(self):
        """Gets the webhook of this InlineResponse202.  # noqa: E501


        :return: The webhook of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._webhook

    @webhook.setter
    def webhook(self, webhook):
        """Sets the webhook of this InlineResponse202.


        :param webhook: The webhook of this InlineResponse202.  # noqa: E501
        :type: object
        """

        self._webhook = webhook

    @property
    def container_group_id(self):
        """Gets the container_group_id of this InlineResponse202.  # noqa: E501


        :return: The container_group_id of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._container_group_id

    @container_group_id.setter
    def container_group_id(self, container_group_id):
        """Sets the container_group_id of this InlineResponse202.


        :param container_group_id: The container_group_id of this InlineResponse202.  # noqa: E501
        :type: object
        """
        if container_group_id is None:
            raise ValueError("Invalid value for `container_group_id`, must not be `None`")  # noqa: E501

        self._container_group_id = container_group_id

    @property
    def compression(self):
        """Gets the compression of this InlineResponse202.  # noqa: E501


        :return: The compression of this InlineResponse202.  # noqa: E501
        :rtype: object
        """
        return self._compression

    @compression.setter
    def compression(self, compression):
        """Sets the compression of this InlineResponse202.


        :param compression: The compression of this InlineResponse202.  # noqa: E501
        :type: object
        """

        self._compression = compression

    @property
    def sync(self):
        """Gets the sync of this InlineResponse202.  # noqa: E501


        :return: The sync of this InlineResponse202.  # noqa: E501
        :rtype: JobsSync
        """
        return self._sync

    @sync.setter
    def sync(self, sync):
        """Sets the sync of this InlineResponse202.


        :param sync: The sync of this InlineResponse202.  # noqa: E501
        :type: JobsSync
        """

        self._sync = sync

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse202, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse202):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
