# coding: utf-8

"""
    🐕 Kelpie API

    API for running long jobs on Salad  # noqa: E501

    OpenAPI spec version: 0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class JobsSync(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'before': 'object',
        'during': 'object',
        'after': 'object'
    }

    attribute_map = {
        'before': 'before',
        'during': 'during',
        'after': 'after'
    }

    def __init__(self, before=None, during=None, after=None):  # noqa: E501
        """JobsSync - a model defined in Swagger"""  # noqa: E501
        self._before = None
        self._during = None
        self._after = None
        self.discriminator = None
        if before is not None:
            self.before = before
        if during is not None:
            self.during = during
        if after is not None:
            self.after = after

    @property
    def before(self):
        """Gets the before of this JobsSync.  # noqa: E501


        :return: The before of this JobsSync.  # noqa: E501
        :rtype: object
        """
        return self._before

    @before.setter
    def before(self, before):
        """Sets the before of this JobsSync.


        :param before: The before of this JobsSync.  # noqa: E501
        :type: object
        """

        self._before = before

    @property
    def during(self):
        """Gets the during of this JobsSync.  # noqa: E501


        :return: The during of this JobsSync.  # noqa: E501
        :rtype: object
        """
        return self._during

    @during.setter
    def during(self, during):
        """Sets the during of this JobsSync.


        :param during: The during of this JobsSync.  # noqa: E501
        :type: object
        """

        self._during = during

    @property
    def after(self):
        """Gets the after of this JobsSync.  # noqa: E501


        :return: The after of this JobsSync.  # noqa: E501
        :rtype: object
        """
        return self._after

    @after.setter
    def after(self, after):
        """Sets the after of this JobsSync.


        :param after: The after of this JobsSync.  # noqa: E501
        :type: object
        """

        self._after = after

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobsSync, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobsSync):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
