# coding: utf-8

"""
    🐕 Kelpie API

    API for running long jobs on Salad  # noqa: E501

    OpenAPI spec version: 0.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ScalingrulesBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'container_group_id': 'object',
        'min_replicas': 'object',
        'max_replicas': 'object',
        'idle_threshold_seconds': 'object'
    }

    attribute_map = {
        'container_group_id': 'container_group_id',
        'min_replicas': 'min_replicas',
        'max_replicas': 'max_replicas',
        'idle_threshold_seconds': 'idle_threshold_seconds'
    }

    def __init__(self, container_group_id=None, min_replicas=None, max_replicas=None, idle_threshold_seconds=None):  # noqa: E501
        """ScalingrulesBody - a model defined in Swagger"""  # noqa: E501
        self._container_group_id = None
        self._min_replicas = None
        self._max_replicas = None
        self._idle_threshold_seconds = None
        self.discriminator = None
        self.container_group_id = container_group_id
        self.min_replicas = min_replicas
        self.max_replicas = max_replicas
        self.idle_threshold_seconds = idle_threshold_seconds

    @property
    def container_group_id(self):
        """Gets the container_group_id of this ScalingrulesBody.  # noqa: E501


        :return: The container_group_id of this ScalingrulesBody.  # noqa: E501
        :rtype: object
        """
        return self._container_group_id

    @container_group_id.setter
    def container_group_id(self, container_group_id):
        """Sets the container_group_id of this ScalingrulesBody.


        :param container_group_id: The container_group_id of this ScalingrulesBody.  # noqa: E501
        :type: object
        """
        if container_group_id is None:
            raise ValueError("Invalid value for `container_group_id`, must not be `None`")  # noqa: E501

        self._container_group_id = container_group_id

    @property
    def min_replicas(self):
        """Gets the min_replicas of this ScalingrulesBody.  # noqa: E501


        :return: The min_replicas of this ScalingrulesBody.  # noqa: E501
        :rtype: object
        """
        return self._min_replicas

    @min_replicas.setter
    def min_replicas(self, min_replicas):
        """Sets the min_replicas of this ScalingrulesBody.


        :param min_replicas: The min_replicas of this ScalingrulesBody.  # noqa: E501
        :type: object
        """
        if min_replicas is None:
            raise ValueError("Invalid value for `min_replicas`, must not be `None`")  # noqa: E501

        self._min_replicas = min_replicas

    @property
    def max_replicas(self):
        """Gets the max_replicas of this ScalingrulesBody.  # noqa: E501


        :return: The max_replicas of this ScalingrulesBody.  # noqa: E501
        :rtype: object
        """
        return self._max_replicas

    @max_replicas.setter
    def max_replicas(self, max_replicas):
        """Sets the max_replicas of this ScalingrulesBody.


        :param max_replicas: The max_replicas of this ScalingrulesBody.  # noqa: E501
        :type: object
        """
        if max_replicas is None:
            raise ValueError("Invalid value for `max_replicas`, must not be `None`")  # noqa: E501

        self._max_replicas = max_replicas

    @property
    def idle_threshold_seconds(self):
        """Gets the idle_threshold_seconds of this ScalingrulesBody.  # noqa: E501


        :return: The idle_threshold_seconds of this ScalingrulesBody.  # noqa: E501
        :rtype: object
        """
        return self._idle_threshold_seconds

    @idle_threshold_seconds.setter
    def idle_threshold_seconds(self, idle_threshold_seconds):
        """Sets the idle_threshold_seconds of this ScalingrulesBody.


        :param idle_threshold_seconds: The idle_threshold_seconds of this ScalingrulesBody.  # noqa: E501
        :type: object
        """
        if idle_threshold_seconds is None:
            raise ValueError("Invalid value for `idle_threshold_seconds`, must not be `None`")  # noqa: E501

        self._idle_threshold_seconds = idle_threshold_seconds

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ScalingrulesBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScalingrulesBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
